# Generated by Django 3.0.4 on 2020-03-14 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_date', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(default='', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(default='', max_length=16)),
                ('guest_password', models.CharField(default='', max_length=40)),
                ('name', models.CharField(default='', max_length=16)),
                ('jumin_no', models.IntegerField(null=True)),
                ('email', models.EmailField(default='email@example.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_img_url', models.TextField(default='')),
                ('receipt_date', models.DateTimeField(auto_now_add=True)),
                ('qr_url', models.TextField(default='')),
                ('flag', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EReceipt.Guests')),
            ],
        ),
        migrations.CreateModel(
            name='Qrcodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode_img_url', models.TextField(default='')),
                ('qrcode_date', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EReceipt.Receipt')),
            ],
        ),
    ]
