# Generated by Django 3.0.4 on 2020-03-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EReceipt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecache',
            name='image_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='imagecache',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
