# Generated by Django 3.0.4 on 2020-03-15 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EReceipt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=16)),
                ('password', models.CharField(default='', max_length=40)),
                ('first_name', models.IntegerField(null=True)),
                ('last_name', models.CharField(default='', max_length=16)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EReceipt.User'),
        ),
        migrations.DeleteModel(
            name='Guests',
        ),
    ]
