# Generated by Django 3.0.4 on 2020-04-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EReceipt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='is_Storage',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_img_uri',
            field=models.TextField(default=''),
        ),
    ]
