# Generated by Django 3.0.4 on 2020-03-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EReceipt', '0002_auto_20200319_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecache',
            name='image',
            field=models.ImageField(default='default_img.jpg', upload_to=''),
        ),
    ]
