# Generated by Django 3.0.4 on 2020-04-27 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EReceipt', '0002_auto_20200426_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='receipt_img_uri',
        ),
        migrations.DeleteModel(
            name='Qrcodes',
        ),
    ]
