# Generated by Django 3.0.4 on 2020-03-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EReceipt', '0002_auto_20200317_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_data', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='media/default_image.jpg', upload_to='')),
            ],
        ),
    ]
