# Generated by Django 3.0.4 on 2020-03-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EReceipt', '0003_auto_20200319_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecache',
            name='device_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
