# Generated by Django 3.0.4 on 2020-03-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EReceipt', '0004_auto_20200316_2316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Devices',
        ),
        migrations.AddField(
            model_name='receipt',
            name='device_id',
            field=models.TextField(default='', max_length=8),
        ),
    ]
