# Generated by Django 3.0.4 on 2020-03-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EReceipt', '0005_auto_20200318_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_data', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='media/default_image.jpg', upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='qrcodes',
            old_name='qrcode_img_url',
            new_name='qr_url',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='flag',
            new_name='is_Storage',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='qr_url',
        ),
    ]
