# Generated by Django 3.0.4 on 2020-04-02 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EReceipt', '0006_auto_20200402_0320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageCache',
        ),
    ]
